# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


=begin

Question.create!(age_number: 1, question_number: 1, text: ' Перестает кричать при взятии на руки или приближении лица взрослого человека.' )
Question.create!(age_number: 1, question_number: 2, text: ' "Замирает" при звуках голоса.' )
Question.create!(age_number: 1, question_number: 3, text: ' Умеет рассматривать лицо и фиксировать взгляд "глаза в глаза" взрослого.' )
Question.create!(age_number: 1, question_number: 4, text: ' Делает "роющие" движения у груди.' )
Question.create!(age_number: 1, question_number: 5, text: ' Удерживает головку при поддержке вертикально.' )
Question.create!(age_number: 2, question_number: 6, text: ' Отвечает улыбкой на улыбку взрослого.' )
Question.create!(age_number: 2, question_number: 7, text: ' Недолго гулит или "гукает".' )
Question.create!(age_number: 2, question_number: 8, text: ' Приподнимает головку и плечики в положении лежа на животе.' )
Question.create!(age_number: 3, question_number: 9, text: ' Ощупывает свои руки, одежду, игрушки.' )
Question.create!(age_number: 3, question_number: 10, text: ' Может "взять" и зажать ладонью игрушку, показанную с расстояния 8-15 см.' )
Question.create!(age_number: 3, question_number: 11, text: ' Может взять игрушку  помахать ею.' )
Question.create!(age_number: 3, question_number: 12, text: ' Поворачивается со спины  на бока, на живот.' )
Question.create!(age_number: 3, question_number: 13, text: ' При кормлении поддерживает ручкой грудь матери или рожок ("помогает").' )
Question.create!(age_number: 3, question_number: 14, text: ' Тащит ногу в рот и сосет большой палец стопы.' )
Question.create!(age_number: 3, question_number: 15, text: ' Прослеживает медленно движущийся объект глазами и поворотом головы.' )
Question.create!(age_number: 3, question_number: 16, text: ' Ищет глазами источник звука, поворачивает голову и шею.' )
Question.create!(age_number: 3, question_number: 17, text: ' Различает приятные и неприятные.' )
Question.create!(age_number: 3, question_number: 18, text: ' Оглядывается в новом помещении (окружении).' )
Question.create!(age_number: 4, question_number: 19, text: ' Плачет при прерывании игры.' )
Question.create!(age_number: 4, question_number: 20, text: ' Понимает интонации голоса.' )
Question.create!(age_number: 4, question_number: 21, text: ' Отличает близких от чужих по внешнему виду.' )
Question.create!(age_number: 4, question_number: 22, text: ' Может произносить много согласных звуков, например:  В, С, Ш, М, Н, Ф, З.' )
Question.create!(age_number: 4, question_number: 23, text: ' Поворачивает голову в сторону взрослого, произносящего его имя.' )
Question.create!(age_number: 4, question_number: 24, text: ' Улыбается своему отражению в зеркале.' )
Question.create!(age_number: 4, question_number: 25, text: ' Подражает последовательности из нескольких звуков.' )
Question.create!(age_number: 4, question_number: 26, text: ' Произносит слоги: МА, ПА, БА, ДА.' )
Question.create!(age_number: 4, question_number: 27, text: ' Произносит несколько звуков на одном дыхании.' )
Question.create!(age_number: 4, question_number: 28, text: ' Понимает запрет, выраженный интонацией голоса или словом "нельзя".' )
Question.create!(age_number: 4, question_number: 29, text: ' Протестует, будучи оставлен в одиночестве.' )
Question.create!(age_number: 4, question_number: 30, text: ' Радуется изображению в зеркале и гладит его.' )
Question.create!(age_number: 4, question_number: 31, text: ' Любит играть в "тю-тю" или "поймай меня".' )
Question.create!(age_number: 4, question_number: 32, text: ' Выполняет "дай ручку", "ладушки".' )
Question.create!(age_number: 4, question_number: 33, text: ' На вопрос "Где?" ищет и находит названный предмет взглядом.' )
Question.create!(age_number: 4, question_number: 34, text: ' Устойчиво сидит (не падает) от нескольких минут до получаса.' )
Question.create!(age_number: 4, question_number: 35, text: ' Ползает на животе, отталкиваясь ногами и подтягиваясь руками.' )
Question.create!(age_number: 4, question_number: 36, text: ' При ползании умеет встать на четвереньки.' )
Question.create!(age_number: 4, question_number: 37, text: ' Стучит игрушкой по столу.' )
Question.create!(age_number: 4, question_number: 38, text: ' Держит в каждой руке по игрушке и стучит ими друг о друга.' )
Question.create!(age_number: 4, question_number: 39, text: ' Отбрасывает то, что не нравится.' )
Question.create!(age_number: 4, question_number: 40, text: ' Перекладывает игрушку из одной руки в другую.' )
Question.create!(age_number: 4, question_number: 41, text: ' Поворачивается с живота на спину.' )
Question.create!(age_number: 4, question_number: 42, text: ' Вытягивает ленту и манипулирует ею.' )
Question.create!(age_number: 4, question_number: 43, text: ' Все тащит в рот.' )
Question.create!(age_number: 4, question_number: 44, text: ' Любит сосать пальцы руки.' )
Question.create!(age_number: 4, question_number: 45, text: ' Встает на ноги, ухватившись за мебель.' )
Question.create!(age_number: 4, question_number: 46, text: ' Использует "клешневой" захват игрушек (большой палец против всех других).' )
Question.create!(age_number: 4, question_number: 47, text: ' Может ползти, зажав в руке игрушку.' )
Question.create!(age_number: 4, question_number: 48, text: ' В стоячем положении ставит одну ногу впереди другой.' )
Question.create!(age_number: 4, question_number: 49, text: ' Знает (показывает) части лица.' )
Question.create!(age_number: 4, question_number: 50, text: ' Рассматривает мелкие детали  и части в игрушке  или рисунке.' )
Question.create!(age_number: 4, question_number: 51, text: ' Имеет четкие вкусовые привязанности.' )
Question.create!(age_number: 4, question_number: 52, text: ' Предпочитает игрушки, звучащие и шумящие.' )
Question.create!(age_number: 4, question_number: 53, text: ' Перестает кричать при звуках музыки.' )
Question.create!(age_number: 4, question_number: 54, text: ' Тщательно, со всех сторон рассматривает игрушки и предметы, пытается их разобрать или изменить их форму и облик.' )
Question.create!(age_number: 4, question_number: 55, text: ' Перекладывает предмет из одной руки в другую.' )
Question.create!(age_number: 4, question_number: 56, text: ' Держит чашку и пытается пить из чашки.' )
Question.create!(age_number: 4, question_number: 57, text: ' Сам держит и ест печенье или сухарик.' )
Question.create!(age_number: 5, question_number: 58, text: ' По просьбе "Дай" находит и дает знакомые предметы.' )
Question.create!(age_number: 5, question_number: 59, text: ' Лепечет с подражанием или передразниваем взрослого в произнесении слогов.' )
Question.create!(age_number: 5, question_number: 60, text: ' Машет ручками: "бай-бай".' )
Question.create!(age_number: 5, question_number: 61, text: ' Выполняет простые указания при игре или кормлении и одевании.' )
Question.create!(age_number: 5, question_number: 62, text: ' Пытается противостоять нежелательным для него указаниям или запретам.' )
Question.create!(age_number: 5, question_number: 63, text: ' Реагирует на свое имя адекватно и постоянно.' )
Question.create!(age_number: 5, question_number: 64, text: ' Заражается настроением других детей, находящихся рядом: плачет и смеется вместе с ними.' )
Question.create!(age_number: 5, question_number: 65, text: ' Дает представления: повторяет действия или звуки, которые вызывали смех или аплодисменты.' )
Question.create!(age_number: 5, question_number: 66, text: ' Демонстрирует подражательное поведение: кормит, причесывает куклу, нагружает машину.' )
Question.create!(age_number: 5, question_number: 67, text: ' Ярко выражает мимикой все настроения: грусть, обиду, гнев, радость.' )
Question.create!(age_number: 5, question_number: 68, text: ' Сбрасывает игрушки и предметы для того, чтобы окружающие взрослые их поднимали.' )
Question.create!(age_number: 5, question_number: 69, text: '  Строит башню из двух кубиков.' )
Question.create!(age_number: 5, question_number: 70, text: ' Манипулирует двумя игрушками сразу - по одной в разных руках.' )
Question.create!(age_number: 5, question_number: 71, text: ' Влезает на кресло и слезает с него.' )
Question.create!(age_number: 5, question_number: 72, text: ' Маленький предмет берет двумя пальцами.' )
Question.create!(age_number: 5, question_number: 73, text: ' Большой предмет берет двумя руками.' )
Question.create!(age_number: 5, question_number: 74, text: ' Ползает уверенно во все стороны.' )
Question.create!(age_number: 5, question_number: 75, text: ' Заползает на ступеньки лестницы.' )
Question.create!(age_number: 5, question_number: 76, text: ' Выявляется право - или леворукость.' )
Question.create!(age_number: 5, question_number: 77, text: ' Садится из положения стоя.' )
Question.create!(age_number: 5, question_number: 78, text: ' Нагибается из  положения  стоя, чтобы поднять что-либо.' )
Question.create!(age_number: 5, question_number: 79, text: ' Сидит на корточках.' )
Question.create!(age_number: 5, question_number: 80, text: ' Может встать на цыпочки.' )
Question.create!(age_number: 5, question_number: 81, text: ' Встает и ходит  при  поддержке за руки.' )
Question.create!(age_number: 5, question_number: 82, text: ' Реагирует на  ритмическую   музыку  движениями тела типа качания или приседания, подпрыгивания.' )
Question.create!(age_number: 5, question_number: 83, text: ' Находит игрушку, спрятанную у него на глазах.' )
Question.create!(age_number: 5, question_number: 84, text: ' Знает (показывает) части тела.' )
Question.create!(age_number: 5, question_number: 85, text: ' Вспоминает игры предыдущего дня.' )
Question.create!(age_number: 5, question_number: 86, text: ' Имеет предпочтения к каким-то играм или игрушкам.' )
Question.create!(age_number: 5, question_number: 87, text: ' Берет чашку за ручку, чтобы пить из нее.' )
Question.create!(age_number: 5, question_number: 88, text: ' Может подносить ложку ко рту.' )
Question.create!(age_number: 5, question_number: 89, text: ' Снимает носки.' )
Question.create!(age_number: 5, question_number: 90, text: ' Помогает одевать себя.' )
Question.create!(age_number: 5, question_number: 91, text: ' Без помощи пьет из чашки или стакана.' )
Question.create!(age_number: 5, question_number: 92, text: ' Открывает ящики столов и шкафов.' )
Question.create!(age_number: 5, question_number: 93, text: ' Развязывает шнурки на обуви и одежде.' )
Question.create!(age_number: 5, question_number: 94, text: ' Листает страницы книги (не всегда по одной).' )
Question.create!(age_number: 5, question_number: 95, text: ' Открывает крышки коробок или кастрюль.' )
Question.create!(age_number: 6, question_number: 96, text: ' Говорит "мама" и еще одно-два слова.' )
Question.create!(age_number: 6, question_number: 97, text: ' Чувствует и выражает свою вину.' )
Question.create!(age_number: 6, question_number: 98, text: ' Старается заслужить одобрение взрослого.' )
Question.create!(age_number: 6, question_number: 99, text: ' Имеет любимую игрушку, о которой заботится.' )
Question.create!(age_number: 6, question_number: 100, text: ' С интересом рассматривает картинки.' )
Question.create!(age_number: 6, question_number: 101, text: ' Произносит 5-10 упрощенных слов.' )
Question.create!(age_number: 6, question_number: 102, text: ' Ухаживает за любимой куклой или медвежонком.' )
Question.create!(age_number: 6, question_number: 103, text: ' Самостоятельно ходит.' )
Question.create!(age_number: 6, question_number: 104, text: ' Заползает на ступеньки лестницы и сползает с них.' )
Question.create!(age_number: 6, question_number: 105, text: ' Поднимается из позиции на корточках.' )
Question.create!(age_number: 6, question_number: 106, text: ' Набирает сразу несколько игрушек, держит их во рту, под мышкой и в руках.' )
Question.create!(age_number: 6, question_number: 107, text: ' Ищет потерянный предмет, помня его постоянное местоположение.' )
Question.create!(age_number: 6, question_number: 108, text: ' Ест с ложки густую пищу сам.' )
Question.create!(age_number: 7, question_number: 109, text: ' Полностью называет предмет в момент заинтересованности.' )
Question.create!(age_number: 7, question_number: 110, text: ' Узнает предметы, игрушки и животных на рисунках книг и журналов.' )
Question.create!(age_number: 7, question_number: 111, text: ' Имеет в словаре несколько десятков упрощенных слов.' )
Question.create!(age_number: 7, question_number: 112, text: ' Узнает знакомого взрослого по фотографии.' )
Question.create!(age_number: 7, question_number: 113, text: ' Катит мяч к взрослому, приглашая к игре.' )
Question.create!(age_number: 7, question_number: 114, text: ' Приседает.' )
Question.create!(age_number: 7, question_number: 115, text: ' Перешагивает через препятствия.' )
Question.create!(age_number: 7, question_number: 116, text: ' Отличает большой и маленький предметы.' )
Question.create!(age_number: 8, question_number: 117, text: ' На прогулке играет в одиночку.' )
Question.create!(age_number: 8, question_number: 118, text: 'На прогулке наблюдает за игрой других детей.' )
Question.create!(age_number: 8, question_number: 119, text: ' Разыскивает на картинках изображения животных, игрушек, предметов, цветов, называемых взрослым.' )
Question.create!(age_number: 8, question_number: 120, text: ' Идет вверх по лестнице (2 шага на ступеньку).' )
Question.create!(age_number: 8, question_number: 121, text: ' Отличает шарик, кубик и кирпичик.' )
Question.create!(age_number: 8, question_number: 122, text: ' Возводит несложные постройки из кубиков или конструктора (скамейка, ворота, дом).' )
Question.create!(age_number: 8, question_number: 123, text: ' Жует пищу.' )
Question.create!(age_number: 8, question_number: 124, text: ' Ест с ложки жидкую пищу и не обливается.' )
Question.create!(age_number: 9, question_number: 125, text: ' Во время игры поясняет свои действия словами и предложениями из двух слов.' )
Question.create!(age_number: 9, question_number:  126, text: ' Играет в одиночку, но около других играющих детей.' )
Question.create!(age_number: 9, question_number: 127, text: ' Подбирает по картинке основные геометрические фигуры типа круга, прямоугольника, треугольника.' )
Question.create!(age_number: 9, question_number: 128, text: ' Подбирает по просьбе предметы четырех основных цветов.' )
Question.create!(age_number: 9, question_number: 129, text: ' Разворачивает и ест конфету.' )
Question.create!(age_number: 9, question_number: 130, text: ' Просится в туалет.' )
Question.create!(age_number: 9, question_number: 131, text: ' Снимает пальто или платье сам.' )
Question.create!(age_number: 10, question_number:  132, text: ' При общении использует предложения из 2-3 слов с включением прилагательных, местоимений и глаголов.' )
Question.create!(age_number: 10, question_number: 133, text: ' Знает и употребляет слово "Я".' )
Question.create!(age_number: 10, question_number: 134, text: ' Появляются вопросы "Где?", "Куда?", "Откуда?".' )
Question.create!(age_number: 10, question_number: 135, text: ' Пинает  мяч ногой и при этом не падает.' )
Question.create!(age_number: 10, question_number: 136, text: ' Понимает рассказ о событии, имевшем место в его жизни и опыте.' )
Question.create!(age_number: 10, question_number: 137, text: ' Строит башню из нескольких кубиков.' )
Question.create!(age_number: 11, question_number: 138, text: ' Копирует вертикальную линию.' )
Question.create!(age_number: 11, question_number: 139, text: ' Спускается по лестнице (1 шаг на ступеньку).' )
Question.create!(age_number: 11, question_number: 140, text: ' Придумывает игры.' )
Question.create!(age_number: 11, question_number: 141, text: ' Сам наливает себе воду, молоко или сок для питья.' )
Question.create!(age_number: 11, question_number: 142, text: ' Ест вилкой.' )
Question.create!(age_number: 11, question_number: 143, text: ' Вытирает руки полотенцем (после мытья).' )
Question.create!(age_number: 11, question_number: 144, text: ' Сам надевает пальто или платье (без застегивания).' )
Question.create!(age_number: 11, question_number: 145, text: ' Может резать ножницами.' )
Question.create!(age_number: 11, question_number: 146, text: ' Сам моет руки и вытирает руки.' )
Question.create!(age_number: 12, question_number: 147, text: ' В речи использует множественное число.' )
Question.create!(age_number: 12, question_number: 148, text: ' Прыгает на двух прижатых одна к другой ногах.' )
Question.create!(age_number: 12, question_number: 149, text: ' Копирует круг.' )
Question.create!(age_number: 12, question_number: 150, text: ' Катается на трехколесном велосипеде.' )
Question.create!(age_number: 12, question_number: 151, text: ' Повторяет фразы и короткие стихи.' )
Question.create!(age_number: 12, question_number: 152, text: ' Самостоятельно играет в ролевую игру - представляет маму, продавца, шофера, волка и т.' )
Question.create!(age_number: 12, question_number: 153, text: ' Называет 4 основных  цвета.' )
Question.create!(age_number: 12, question_number: 154, text: ' Может рассказать о событии, картинке, мультике.' )
Question.create!(age_number: 12, question_number: 155, text: ' Может несколько секунд балансировать на одной ноге.' )
Question.create!(age_number: 12, question_number: 156, text: ' Воспроизводит сложные сюжетные постройки из кубиков или конструктора (дом с забором и дорогой).' )
Question.create!(age_number: 12, question_number: 157, text: ' Одевается почти полностью без помощи взрослых (без части пуговиц и шнурков).' )
Question.create!(age_number: 12, question_number: 158, text: ' Пользуется салфеткой или носовым платком  (по мере необходимости).' )

=end